const GET_ALL_THREADS = 'GET_ALL_THREADS'
const GET_THREAD_SUBJECTS = 'GET_THREAD_SUBJECTS'
const ACTIVATE_THREAD = 'ACTIVATE_THREAD'
const DEACTIVATE_THREAD = '.DEACTIVATE_THREAD'

export default {
  GET_ALL_THREADS,
  GET_THREAD_SUBJECTS,
  ACTIVATE_THREAD,
  DEACTIVATE_THREAD,
}
