const WS_CONNECT = 'WS_CONNECT'
const WS_SEND = 'WS_SEND'
const WS_SAVE_MESSAGE = 'WS_SAVE_MESSAGE'
const WS_DISCONNECT = 'WS_DISCONNECT'
const GET_ROOMS_LIST = 'GET_ROOMS_LIST'

export default {
    WS_CONNECT,
    WS_SEND,
    WS_SAVE_MESSAGE,
    WS_DISCONNECT,
    GET_ROOMS_LIST
}