const WS_CONNECT = 'WS_CONNECT'
const WS_CONNECTING = 'WS_CONNECTING'
const WS_CONNECTED = 'WS_CONNECTED'
const WS_DISCONNECT = 'WS_DISCONNECT'
const WS_DISCONNECTED = 'WS_DISCONNECTED'
const WS_SAVE_MESSAGE = 'WS_SAVE_MESSAGE'

export default {
    WS_CONNECT,
    WS_CONNECTING,
    WS_CONNECTED,
    WS_DISCONNECT,
    WS_DISCONNECTED,
    WS_SAVE_MESSAGE
}