const GET_SUBJECT_COMMENTS = 'GET_SUBJECT_COMMENTS'
const ACTIVATE = 'ACTIVATE'
const DEACTIVATE = 'DEACTIVATE'
const ADD_COMMENT = 'ADD_COMMENT'

export default{
  GET_SUBJECT_COMMENTS,
  ACTIVATE,
  DEACTIVATE,
  ADD_COMMENT
}
