const GET_CANDLES_CHART = 'GET_CANDLES_CHART'
const GET_USER_TRIGGERS = 'GET_USER_TRIGGERS'
const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS'
const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS'
const ADD_NEW_TRIGGER = 'ADD_NEW_TRIGGER'
const NEW_PROGNOSIS = 'NEW_PROGNOSIS'
const RESET = 'RESET'

export default {
  GET_CANDLES_CHART,
  GET_USER_TRIGGERS,
  GET_USER_NOTIFICATIONS,
  GET_USER_TRANSACTIONS,
  ADD_NEW_TRIGGER,
  NEW_PROGNOSIS,
  RESET
}
